{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOY1LpfBbVyn5n7BMDV0440"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "OhQpyPIdMnIY"
      },
      "outputs": [],
      "source": [
        "import firebase_admin\n",
        "from firebase_admin import credentials\n",
        "from firebase_admin import firestore\n",
        "import json\n",
        "import uuid\n",
        "from dataclasses import *\n",
        "\n",
        "#Definindo as credenciais do Firebase\n",
        "# cred = credentials.Certificate(\"#\")\n",
        "\n",
        "#Checando se a seção está online\n",
        "if not firebase_admin._apps:\n",
        "    firebase_admin.initialize_app(cred)\n",
        "\n",
        "#Criando o cliente\n",
        "db = firestore.client()\n",
        "\n",
        "Cards = [{\n",
        "     'Comprador' : 'Eu',\n",
        "     'Origem' : '',\n",
        "     'Destino' : '',\n",
        "     'Data' : '',\n",
        "     'Num_animais' : '',\n",
        "     'ID': str(uuid.uuid4())\n",
        "}]\n",
        "\n",
        "Cards.append({\"Comprador\": \"Nulo\", \"ID\": str(uuid.uuid4())})\n",
        "\n",
        "#ADICIONAR LISTA PARA JSON\n",
        "\n",
        "def jsonAdicionarLista(lista: list):\n",
        "  jsonDicionarios = json.dumps(lista, indent = 4)\n",
        "  #print(jsonDicionarios)\n",
        "  return jsonDicionarios\n",
        "\n",
        "# ADICIONAR JSON PARA FIREBASE\n",
        "\n",
        "def fbAdicionarJson(jsonCards: json):\n",
        "  jsonLista = json.loads(jsonCards)\n",
        "  for index, dicionario in enumerate(jsonLista):\n",
        "    db.collection(\"Cards\").document(dicionario.get('ID')).set(jsonLista[index])\n",
        "\n",
        "# BAIXAR DO FIREBASE PARA JSON\n",
        "\n",
        "def jsonBaixarFB():\n",
        "  teste = []\n",
        "  campos_desejados = ['Comprador', 'Origem', 'Destino', 'Data', 'Num_animais', 'ID']\n",
        "  for doc in db.collection(\"Cards\").stream():\n",
        "      dados_ordenados = {campo: doc.to_dict().get(campo) for campo in campos_desejados if campo in doc.to_dict()}\n",
        "      teste.append(dados_ordenados)\n",
        "  return json.dumps(teste, indent = 4)\n",
        "\n",
        "# ADICIONAR JSON PARA LISTA\n",
        "\n",
        "\n",
        "\n",
        "# testi = jsonBaixarFB()\n",
        "# print(testi)\n",
        "# for doc in db.collection(\"Cards\").stream():\n",
        "#     for campo in campos_desejados:\n",
        "#         if campo in doc.to_dict():\n",
        "#           print(f'{campo}: {doc.to_dict()[campo]}, ', end='')\n",
        "\n",
        "# teste = jsonAdicionarLista(Cards)\n",
        "# print(teste)\n",
        "# fbAdicionarJson(teste)\n",
        "\n",
        "\n",
        "#alterar\n",
        "\n",
        "#excluir\n",
        "\n",
        "##JSON\n",
        "\n",
        "#criar\n",
        "\n",
        "#alterar\n",
        "\n",
        "#excluir\n",
        "\n",
        "##CHECK ONLINE-OFFLINE\n",
        "\n",
        "\n",
        "###recursivo\n",
        "\n"
      ]
    }
  ]
}